### ISSUE TITLE
Add CLI interface for non-interactive

### ISSUE THREAD

**Issue by MewX** [MewX/KanTV-downloader-cli#4]
Using bazel + gazelle builds.

Going to support non-interactive cli mode only.

CLI module:
- https://github.com/spf13/cobra
- https://github.com/urfave/cli (preferred)

Should provide place holder arguments:

- [x] login #3
- [x] info/config: n_thread, user_agent, cache_size, max_parallel, max_download_file (need to copy codes from BaidupanPCS-Go,  savedir #12
- [x] download one movie and all episodes - with save folder/file name #8 #9 #10 #11
- [ ] search, result paging #7
- [x] register #5
- [x] anonymous mode (web API: using wechat watch code) #6
- [x] set proxy (http/https/auto/socks5)
- [x] override cookies
- [ ] exit

**Comment by MewX** [comment]
Each placeholder should be tracked in separate issues

**Comment by MewX** [comment]
Used cobra because `urfave/cli` has some dependencies which couldn't be auto-recognised by gazelle.
